force-app/main/default/objects/Document__c/Document__c.object-meta.xml
<CustomObject>
    <label>Document</label>
    <nameField>
        <label>Document Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Documents</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Document__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>This used to link Account with Document</description>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Contact__c.field-meta.xml
<CustomField>
    <fullName>Contact__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Contact</label>
    <referenceTo>Contact</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Customer_Notified_At__c.field-meta.xml
<CustomField>
    <fullName>Customer_Notified_At__c</fullName>
    <description>This field is used as a datetime timestamp of when the customer was notified about the doc.</description>
    <label>Customer Notified At</label>
    <type>DateTime</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Generation_Date__c.field-meta.xml
<CustomField>
    <fullName>Generation_Date__c</fullName>
    <description>This field is used to store when was document generated at the bank.</description>
    <label>Generation Date</label>
    <type>Date</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Notification_Status__c.field-meta.xml
<CustomField>
    <fullName>Notification_Status__c</fullName>
    <label>Notification Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Customer Notified</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Document__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Product</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Documents</relationshipLabel>
    <relationshipName>Documents</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Document__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Report</fullName>
            </value>
            <value>
                <fullName>Transactional</fullName>
            </value>
            <value>
                <fullName>Legal</fullName>
            </value>
            <value>
                <fullName>Contract</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/SendEmailBatch.cls
public class SendEmailBatch implements Database.Batchable<SObject>, Database.Stateful {
    private Map<Id, Id> contactIdToUserIdMap;
    
    public SendEmailBatch() {
        contactIdToUserIdMap = new Map<Id, Id>();
    }
    
    public Database.QueryLocator start(Database.BatchableContext context) {
        // Query all community users where ContactId is not null
        for (User user : [SELECT Id, ContactId FROM User WHERE ContactId != null]) {
            contactIdToUserIdMap.put(user.ContactId, user.Id);
        }
        return Database.getQueryLocator([SELECT Id, Name, Type__c, Notification_Status__c,Generation_Date__c, Customer_Notified_At__c, Account__c, Contact__c, Contact__r.Email, Product__c, CreatedDate, 
                                         (SELECT ContentDocumentId, LinkedEntityId, ContentDocument.LatestPublishedVersionId, ContentDocument.LatestPublishedVersion.Title, ContentDocument.LatestPublishedVersion.FileExtension, ContentDocument.LatestPublishedVersion.VersionData FROM ContentDocumentLinks)
                                         FROM Document__c WHERE Notification_Status__c = 'New']);
    }
    
    public void execute(Database.BatchableContext context, List<Document__c> documentList) {
        
        Map<Id, Map<String, List<Document__c>>> contactDocumentMap = new Map<Id, Map<String, List<Document__c>>>();
        List<Document__c> documentListToUpdate = new List<Document__c>();
        
        // Group documents by customer and document type
        for (Document__c doc : documentList) {
            String docType = doc.Type__c;
            Id contactId = doc.Contact__c;
            
            if (!contactDocumentMap.containsKey(contactId)) {
                contactDocumentMap.put(contactId, new Map<String, List<Document__c>>());
            }
            
            Map<String, List<Document__c>> documentTypeMap = contactDocumentMap.get(contactId);
            if (!documentTypeMap.containsKey(docType)) {
                documentTypeMap.put(docType, new List<Document__c>());
            }
            
            List<Document__c> documents = documentTypeMap.get(docType);
            documents.add(doc);
        }
        
        // List of email instances
        List<Messaging.SingleEmailMessage> sendEmailList = new List<Messaging.SingleEmailMessage>();
        
        // Send emails for each document type to respective contacts
        for (Id contactId : contactDocumentMap.keySet()) {
            Map<String, List<Document__c>> documentTypeMap = contactDocumentMap.get(contactId);
            
            for (String docType : documentTypeMap.keySet()) {
                List<Document__c> documents = documentTypeMap.get(docType);               
                String recipientId = (!contactIdToUserIdMap.isEmpty() && contactIdToUserIdMap.containsKey(contactId)) ? contactIdToUserIdMap.get(contactId) : contactId;
                Messaging.SingleEmailMessage email = new Messaging.SingleEmailMessage();    
                email.setTargetObjectId(recipientId);
                //email.setSaveAsActivity(true);
                email.setSubject('New ' + docType + ' Document(s) Available: ');
                
                // Compose email content with document list
                String listOfDocuments = '';
                for (Integer i = 0; i < documents.size(); i++) {
                    listOfDocuments += (i+1) + '. ' + documents[i].Name + '\n';
                }
                email.setPlainTextBody('New ' + docType + ' Document(s) are available and attached in the mail. PFB list of Documents:' + '\n' + listOfDocuments);
                
                List<Messaging.EmailFileAttachment> emailAttachments = new List<Messaging.EmailFileAttachment>(); // List to store attachments
                
                // Attach documents to the email
                for (Document__c document : documents) {
                    for (ContentDocumentLink conDocLink : document.ContentDocumentLinks) {
                        Messaging.EmailFileAttachment emailAttachment = new Messaging.EmailFileAttachment();
                        Blob fileData = conDocLink.ContentDocument.LatestPublishedVersion.VersionData;
                        emailAttachment.setFileName(conDocLink.ContentDocument.LatestPublishedVersion.Title + '.' + conDocLink.ContentDocument.LatestPublishedVersion.FileExtension);
                        emailAttachment.setBody(fileData);
                        emailAttachments.add(emailAttachment); // Add attachment to the list
                    }
                    
                    // Update document status and timestamp
                    document.Notification_Status__c = 'Customer Notified';
                    document.Customer_Notified_At__c = System.Now();
                    
                    // Add document to the update list
                    documentListToUpdate.add(document);
                }
                
                // Set all attachments on the email
                email.setFileAttachments(emailAttachments);
                
                // Add the email instance in the list
                sendEmailList.add(email);
            }
        }
        
        // Send all emails in one call
        if (!sendEmailList.isEmpty()) {
            System.debug('sendEmailList.size()'+sendEmailList.size());
            System.debug('sendEmailList'+sendEmailList);
            //Messaging.sendEmail(sendEmailList);            
        }
        
        // Update documents in the database together from list
        if (!documentListToUpdate.isEmpty()) {
            Database.update(documentListToUpdate, false);
        }
        
    }
    
    public void finish(Database.BatchableContext context) {
        // Perform any cleanup or post-processing tasks if needed
    }
}